pool:
  vmImage: 'ubuntu-latest'
variables:
  FORCE_COLOR: 1
jobs:
  - job: PRBuild
    displayName: PR Build
    variables:
      NodeVersion: 16
    steps:
      - checkout: self
      - template: templates/build.yaml
