pr: none
trigger: main
parameters:
  - name: sites
    type: object
    displayName: 'Sites to include'
    default: ['rushjs.io', 'rushstack.io', 'api.rushstack.io']
pool:
  vmImage: 'ubuntu-latest'
variables:
  FORCE_COLOR: 1
jobs:
  - job: Deploy
    displayName: Deploy
    variables:
      NodeVersion: 14
    steps:
      - checkout: self
      - template: templates/build.yaml
      - ${{ each site in parameters.sites }}:
          - script: 'node ../../common/scripts/install-run-rushx.js deploy'
            displayName: 'Deploy ${{ site }}'
            workingDirectory: 'websites/${{ site }}'
            env:
              GITHUB_USER: insert-bot-user-here
