pr: none
trigger: none
parameters:
  - name: sites
    type: object
    displayName: 'Sites to include'
    default: [
        'api-extractor.com'
        # 'api.rushstack.io',
        # 'heft.rushstack.io',
        # 'lfx.rushstack.io',
        # 'rushjs.io',
        # 'rushstack.io',
        # 'tsdoc.org'
      ]
pool:
  vmImage: 'ubuntu-latest'
variables:
  FORCE_COLOR: 1
  group: 'Rushstack-Websites Publishing'
jobs:
  - job: Deploy
    displayName: Deploy
    variables:
      NodeVersion: 16
    steps:
      - checkout: self
        persistCredentials: true
      - template: templates/build.yaml
      - script: |
          git config credential.helper "!f() { echo \"username=${GIT_USER}\\npassword=${GIT_TOKEN}\"; }; f"
        displayName: 'Configure Git credentials'
        env:
          GIT_USER: rushbot
          GIT_TOKEN: $(System.AccessToken)
      - ${{ each site in parameters.sites }}:
          - script: 'node ../../common/scripts/install-run-rushx.js deploy'
            displayName: 'Deploy ${{ site }}'
            workingDirectory: 'websites/${{ site }}'
            env:
              TARGET: prod
              GIT_USER: rushbot
              GIT_TOKEN: $(System.AccessToken)
